[package]
name = "uri"
version = "0.1.0"
authors = ["Richard Walters <rwalters@digitalstirling.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"

[dev-dependencies]
uriparse = "0.6"
